"""create user

Revision ID: f713cca7ad47
Revises:
Create Date: 2026-04-22 14:52:10.345355

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f713cca7ad47"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.execute("CREATE SCHEMA general")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("login", sa.String(), nullable=False, comment="Логин"),
        sa.Column("password", sa.String(), nullable=False, comment="Пароль"),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="general",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    op.execute("DROP SCHEMA general CASCADE")
